version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: app
    ports:
      - "3004:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
